### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by pasawaya** [xyfeng/XYOrigami#3]
I added your library to my project and imported it into a view controller. In a method, I transition from one view to another using the "showOrigamiTransitionWith:NumberOfFolds:..." method. When I attempt to build, the build fails with the following errors (sorry that the error is long):

<pre><code>
Ld "/Users/John/Library/Developer/Xcode/DerivedData/Guess_Who!-cladfxruebegwfgbwcdufbpbuldh/Build/Products/Debug-iphonesimulator/Guess Who!.app/Guess Who!" normal i386
    cd "/Projects/Technology/Programming/Programming Projects/Objective-C Programs/iPhone Applications/Projects/Guess Who!"
    setenv MACOSX_DEPLOYMENT_TARGET 10.6
    setenv PATH "/Applications/Developer/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Developer/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Developer/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Developer/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk "-L/Users/John/Library/Developer/Xcode/DerivedData/Guess_Who!-cladfxruebegwfgbwcdufbpbuldh/Build/Products/Debug-iphonesimulator" "-F/Users/John/Library/Developer/Xcode/DerivedData/Guess_Who!-cladfxruebegwfgbwcdufbpbuldh/Build/Products/Debug-iphonesimulator" -filelist "/Users/John/Library/Developer/Xcode/DerivedData/Guess_Who!-cladfxruebegwfgbwcdufbpbuldh/Build/Intermediates/Guess Who!.build/Debug-iphonesimulator/Guess Who!.build/Objects-normal/i386/Guess Who!.LinkFileList" -mmacosx-version-min=10.6 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -Xlinker -no_implicit_dylibs -D__IPHONE_OS_VERSION_MIN_REQUIRED=50100 -framework AddressBook -framework UIKit -framework Foundation -framework CoreGraphics -o "/Users/John/Library/Developer/Xcode/DerivedData/Guess_Who!-cladfxruebegwfgbwcdufbpbuldh/Build/Products/Debug-iphonesimulator/Guess Who!.app/Guess Who!"

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CAKeyframeAnimation", referenced from:
      objc-class-ref in UIView+Origami.o
      l_OBJC_$_CATEGORY_CAKeyframeAnimation_$_Parametric in UIView+Origami.o
  "_OBJC_CLASS_$_CATransformLayer", referenced from:
      objc-class-ref in UIView+Origami.o
  "_OBJC_CLASS_$_CALayer", referenced from:
      objc-class-ref in UIView+Origami.o
  "_OBJC_CLASS_$_CAGradientLayer", referenced from:
      objc-class-ref in UIView+Origami.o
  "_OBJC_CLASS_$_CABasicAnimation", referenced from:
      objc-class-ref in UIView+Origami.o
  "_OBJC_CLASS_$_CATransaction", referenced from:
      objc-class-ref in UIView+Origami.o
  "_CATransform3DIdentity", referenced from:
      -[UIView(Origami) showOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
      -[UIView(Origami) hideOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
  "_kCAAnimationLinear", referenced from:
      +[CAKeyframeAnimation(Parametric) animationWithKeyPath:function:fromValue:toValue:] in UIView+Origami.o
  "_kCAFillModeForwards", referenced from:
      -[UIView(Origami) showOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
      -[UIView(Origami) hideOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
  "_kCATransactionAnimationDuration", referenced from:
      -[UIView(Origami) showOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
      -[UIView(Origami) hideOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:] in UIView+Origami.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre>

**Comment by xyfeng** [comment]
That must be the quartzcore framework you need to add to your project.

xy

On Fri, Jun 29, 2012 at 11:51 PM, pasawaya <
reply@reply.github.com

**Comment by pasawaya** [comment]
That fixed it. Sorry about the stupid error. Thanks so much!
