### ISSUE TITLE
showOrigami 'viewB' hiding 'viewA' - hideOrigami 'viewB' showing 'viewC'

### ISSUE THREAD

**Issue by fabiocaccamo** [xyfeng/XYOrigami#4]
Hi! Thank you for sharing this library, it's very nice!

Yesterday I used it in a UITabbarController, I need to use the origami animation just to show / hide 1 view controller (which is a map).
The problem seems to be that when you call the hideOrigami... your class works fine only if you use exactly the same views which you used when you called the showOrigami, but in the navigation flow when I need to hide my map viewcontroller, the view which will be displayed could not match the view previously hidden.

Why the state is static? I could want more instances of the XYOrigami working indipendently...

**Comment by xyfeng** [comment]
Hi Fablo,

The state is static to prevent people call the action multiple times during the animation.
In your case, move the static XYOrigamiTransitionState to the header file, you can change it as you want; or simply get rid of it at your own risk.

best,
xy

**Comment by fabiocaccamo** [comment]
Hi, 
you have not answered to the main issue...

**Comment by xyfeng** [comment]
Did you try to read the code? It's only couple of lines.

The view which will call showOrigami/hideOrigami is the view going to slide
left/right.
The view you are passing to the function are the view will be folded in the
animation.

If the folding view you want to hide didn't show up, make sure you add it.
If you call the hideOrigami without calling the showOrigami, make sure you
change the state.

In the code you will see the slide view and the folding view have the same
superview, before the animation happen,
there are functions to make sure the view are at the right position to run
the animation.

I don't know what's your code structure looks like. This two classes are
bare bone source code to show people how to
make folding animations, not a universal library. And I believe github are
made for people share and learn, not for Q&A.
Please don't abuse it, if it's not a bug.

best,
xy

On Tue, Jul 24, 2012 at 6:15 AM, Fabio Caccamo <
reply@reply.github.com
