### ISSUE TITLE
Allow folding from top and bottom

### ISSUE THREAD

**Issue by JoeKueser** [xyfeng/XYOrigami#6]
I'm trying to add this myself, but my math is a little rusty, and the only animations I have worked with are from tutorials. So I am hoping you can help.

I would like to be able to fold not only from left or right, but also from top or bottom. (In other words, putting the Y in XYOrigami ;-)

I will continue to struggle with this, and will contribute my changes if I ever finish it. If, however, you have the time and the talent and want to add this, I would greatly appreciate it.

Any helpful hints to get me heading in the right direction would also be appreciated. Especially when it comes to the animation, and the math involved to set those up.

**Comment by sridvijay** [comment]
Just wanted to say that I'll try doing it too, if you find anything interesting tell me!

**Comment by xyfeng** [comment]
Sorry for the late reply.

You guys should check out this one, the animation is better implemented. https://github.com/honcheng/PaperFold-for-iOS

I'm extremely busy recently, will try to find a time to add those in the near future.

**Comment by xyfeng** [comment]
Quickly added the top and bottom directions, didn't test through, the code looks a little bit ugly right now, may have bugs, please test and let me know.

**Comment by JoeKueser** [comment]
Most excellent. Thank you. I'll try to test tomorrow.

**Comment by JoeKueser** [comment]
Worked great. I updated the demo in my fork to add the top and bottom options to the xib and resize the map accordingly. Feel free to grab my changes, or improve upon them :-)

https://github.com/JoeKueser/XYOrigami/commit/9f7369a4c3f84843c4c85f8c1a5b00e571b0b3e4
