### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Nineswiss** [xyfeng/XYOrigami#7]
I've tried to integrate with my app to no avail. Error:
[UIView hideOrigamiTransitionWith:NumberOfFolds:Duration:Direction:completion:]: unrecognized selector sent to instance 0x836a830

Code:
[self.webHolder hideOrigamiTransitionWith:self.pinkView NumberOfFolds:2 Duration:0.5 Direction:XYOrigamiDirectionFromLeft completion:^(BOOL finished) {NSLog(@"animation completed.");}];

Any ideas?

**Comment by xyfeng** [comment]
I don't believe this is a bug, you should learn how to debug code by yourself.

**Comment by Nineswiss** [comment]
Cool. I probably posted it in the wrong area. I realize its not a bug but thought you may have come across a similar issue in the past.
